apiVersion: v1
kind: Namespace
metadata:
  name: azuredocs-prod
  labels:
    app.kubernetes.io/part-of: azuredocs-enforcer
    environment: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: azuredocs-staging
  labels:
    app.kubernetes.io/part-of: azuredocs-enforcer
    environment: staging
