apiVersion: batch/v1
kind: CronJob
metadata:
  name: bias-snapshot-generator
  namespace: azuredocs-app
  labels:
    app: bias-snapshot-generator
    component: scheduler
spec:
  schedule: "0 7 * * *"  # Run at 7 AM, 3 hours after doc collection starts
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600  # Auto-delete 1 hour after completion
      template:
        metadata:
          labels:
            app: bias-snapshot-generator
            component: scheduler
            azure.workload.identity/use: "true"
        spec:
          priorityClassName: worker-low-priority
          serviceAccountName: sc-account-fefa7dd8-f9d3-4524-8a35-c1123a838df0
          restartPolicy: Never
          containers:
          - name: bias-snapshot-generator
            image: seanmckdemo.azurecr.io/queue-worker:0.0.54
            imagePullPolicy: Always
            command: ["python", "/app/scripts/update_bias_snapshots.py"]
            env:
            - name: PYTHONPATH
              value: "/app"
            envFrom:
            - secretRef:
                name: sc-azuredocsdbconnection-secret
            resources:
              requests:
                memory: "128Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
          volumes:
          - name: secrets-store
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "azuredocs-secrets"
  # Keep last 3 successful jobs and 3 failed jobs for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  # Don't run overlapping jobs
  concurrencyPolicy: Forbid
  # If a job fails, don't retry - wait for next scheduled run
  suspend: false