apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linuxfirst-docs-prod
  namespace: argocd
spec:
  project: linuxfirst-docs
  source:
    repoURL: git@github.com:seanmck/linuxfirst-azuredocs-enforcer.git
    targetRevision: main
    path: infra/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: azuredocs-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  # No automated block initially - manual sync only
  # Enable after successful cutover:
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - CreateNamespace=true
