apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linuxfirst-docs-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: linuxfirst-docs
  source:
    repoURL: https://github.com/seanmck/linuxfirst-azuredocs-enforcer.git
    targetRevision: main
    path: infra/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: azuredocs-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
