apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-postgres
  namespace: azuredocs-app
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "96c0a94f-d713-4c85-847f-e0e98ffeabb9"
    keyvaultName: "seanmckaksdemo"
    objects: |
      array:
        - |
          objectName: DB_HOST
          objectType: secret
        - |
          objectName: DB_PORT
          objectType: secret
        - |
          objectName: DB_NAME
          objectType: secret
        - |
          objectName: DB_USER
          objectType: secret
        - |
          objectName: DB_PASSWORD
          objectType: secret
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
