apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: azuredocs-app
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: mcp-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: azuredocs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
        - name: mcp-server
          image: <your-dockerhub-username>/mcp-server:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
            - name: RABBITMQ_HOST
              value: "rabbitmq"
          ports:
            - containerPort: 9000
