apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: azuredocs-app
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: mcp-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  namespace: azuredocs-app
  labels:
    app: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
        - name: mcp-server
          image: seanmckdemo.azurecr.io/mcp-server:0.0.6
          env:            
            - name: AZURE_OPENAI_DEPLOYMENT
              valueFrom:
                secretKeyRef:
                  name: azuredocs-secrets
                  key: AZURE_OPENAI_DEPLOYMENT
          envFrom:
            - secretRef:
                name: sc-linuxdocsazureopenai-secret
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mcp-server-scaler
  namespace: azuredocs-app
spec:
  scaleTargetRef:
    name: mcp-server
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 60
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "20"