apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: webui-high-priority
value: 1000
globalDefault: false
description: "High priority for user-facing web UI components"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: worker-normal-priority
value: 500
globalDefault: false
description: "Normal priority for background worker components"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: worker-low-priority
value: 100
globalDefault: false
description: "Low priority for batch processing and non-critical background jobs"