apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azuredocs-secrets
  namespace: azuredocs-app
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "fefa7dd8-f9d3-4524-8a35-c1123a838df0"
    keyvaultName: "seanmckaksdemo"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: admin-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: admin-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: app-secret-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-port
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: rabbitmq-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: rabbitmq-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: github-token
          objectType: secret
          objectVersion: ""
        - |
          objectName: azure-openai-deployment
          objectType: secret
          objectVersion: ""
        - |
          objectName: rabbitmq-connection-string
          objectType: secret
          objectVersion: ""
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"  # Will be substituted during deployment
  secretObjects:
  - secretName: azuredocs-secrets
    type: Opaque
    data:
    - objectName: admin-password
      key: ADMIN_PASSWORD
    - objectName: admin-username
      key: ADMIN_USERNAME
    - objectName: app-secret-key
      key: APP_SECRET_KEY
    - objectName: rabbitmq-username
      key: RABBITMQ_USERNAME
    - objectName: rabbitmq-password
      key: RABBITMQ_PASSWORD
    - objectName: github-token
      key: GITHUB_TOKEN
    - objectName: azure-openai-deployment
      key: AZURE_OPENAI_DEPLOYMENT
    - objectName: rabbitmq-connection-string
      key: RABBITMQ_CONNECTION_STRING
