apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader
  namespace: azuredocs-app
  annotations:
    azure.workload.identity/client-id: "598c9c7b-cf9d-4b5b-9a00-988d9e13e16b"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webui-sa
  namespace: azuredocs-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azuredocs-app-sa
  namespace: azuredocs-app
  annotations:
    azure.workload.identity/client-id: "598c9c7b-cf9d-4b5b-9a00-988d9e13e16b"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-reader-binding
subjects:
- kind: ServiceAccount
  name: secret-reader
  namespace: azuredocs-app
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io